### ISSUE TITLE
[von_neumann] User report of code issues in lecture

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python.myst#297] opened 2022-12-23 01:03 UTC
> recently I came across your excellent program code of the Von Neumann Growth Model on the website: https://python.quantecon.org/von_neumann_model.html#top.
>
>
>
> The codes of the Von Neumann model in the book (“Lectures in Quantitative Economics with Python”) together with Thomas J. Sargent (chapter 71) and on the website (above) are the same. However, when I run the code I got
>
>    (1) no output, and
>
>    (2) in some lines an error message (e.g.., in the line: “Value of the game with γ = 2”; error: invalid syntax).
>
>
>
> Well I work with the latest version of Python in Visual Studio Code. Maybe there are some changes since your coding in 2019.
>
>
>
> Anyway, I would be happy to get a hint why the program does not give outputs, etc.
>

**Comment by mmcky** [comment] 2022-12-23 01:04
@HumphreyYang given the cache is built every time the `main` branch changes -- there doesn't appear to be an execution issue. The issue is not present for the current `live` site. Can you replicate this on your end?

**Comment by HumphreyYang** [comment] 2022-12-23 01:08
Hi @mmcky, I have no issue in my rerun. I am writing an email to Fritz, and I think the error message Fritz shows is caused by the use of an older Python version, which cannot recognize the f-string. Here is the email to Fritz that I intended to send: 

Hi Fritz,
 
Thanks for your feedback. I have rerun the code, and I did not encounter the errors you spotted in your attempt. The attachment is the result of my run, and you can see the environment I am using in the first code block.
 
Based on the error message you provided (‘in the line: “Value of the game with γ = 2”; error: invalid syntax’), it may be an issue with recognizing the f-string, which may indicate you are running on an older Python version in your environment.
 
It would be greatly appreciated if you could provide more information regarding the errors you have.
 
Please let us know if you still run into issues.
 
Best,
Humphrey

**Comment by mmcky** [comment] 2022-12-23 01:09
Nice suggestion - thanks @HumphreyYang

**Comment by HumphreyYang** [comment] 2022-12-23 09:25
The user emailed me that the problem was resolved. Closing this issue now.

**Closed by HumphreyYang** 2022-12-23 09:25 UTC
Labels: bug
